In [25]:
from utils import *
import numpy as np
import pickle
import networkx as nx
import neat
import argparse
from tqdm import tqdm
import re

In [26]:
def output_activation(x, current_balance):
    # scale the output to ensure that the sum of the bids does not exceed the available balance
    x = [max(bid, 0) for bid in x]
    scale_factor = 0
    if sum(x) != 0:
        scale_factor = current_balance / sum(x)
    return [bid * scale_factor for bid in x]

In [27]:
config_file = "monkey_config.cfg"
config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                         neat.DefaultSpeciesSet, neat.DefaultStagnation,
                         config_file)

In [28]:
with open("winning_genome.pkl", "rb") as genome_file:
    winner = pickle.load(genome_file)
winner_net = neat.nn.FeedForwardNetwork.create(winner, config)


In [29]:
#G.10.11
money = 1000
model_input = construct_input("graph_info_s1/G.10.11.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([ 80.,   0.,   0., 298.,   0.,   0.,   0., 548.,  73.,   0.])

In [30]:
#G.10.12
money = 1000
model_input = construct_input("graph_info_s1/G.10.12.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([  1.,  29.,   0., 335.,   0.,   0.,   0., 478.,  41., 116.])

In [31]:
#O.10.13
money = 1000
model_input = construct_input("graph_info_s1/O.10.13.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([ 25.,   0.,   0., 333.,   0.,   0.,   0., 370.,  32., 241.])

In [32]:
# O.10.14
money = 1000
model_input = construct_input("graph_info_s1/O.10.14.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([ 79., 143.,  68.,  77.,   0.,   0.,   0., 527.,   0., 106.])

In [33]:
# J.20.15
money = 1000
model_input = construct_input("graph_info_s1/J.20.15.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([416.,   0.,   8., 231.,   0.,   0.,   0., 132., 212.,   0.])

In [34]:
# J.20.16
money = 1000
model_input = construct_input("graph_info_s1/J.20.16.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([300.,   0.,   0., 476.,   0.,  46.,   0.,  63., 116.,   0.])

In [35]:
# J.30.17
money = 1000
model_input = construct_input("graph_info_s1/J.30.17.html", money)
bids = np.array(output_activation(winner_net.activate(model_input), money)).round()
bids

array([301.,   0.,   0., 294.,   0., 122.,   0., 186.,  98.,   0.])